name: build

on:
  push:
    branches: [lukepighetti/actions]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v1
      - uses: arduino/setup-task@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: task build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - uses: actions/deploy-pages@v1
